### ISSUE TITLE
Add windows support

### ISSUE THREAD

**Issue by oovm** [wasmfx/wasmfxtime#180]
I want to study examples on Windows platform, but wasmtime cannot be compiled on Windows, missing FiberStack:

https://github.com/wasmfx/wasmfxtime/blob/b783f55bd8c287241b5a623c159aa134c9b3b9e9/crates/runtime/src/fibre/mod.rs#L18

But there is a Windows version of FiberStack:

https://github.com/wasmfx/wasmfxtime/blob/b783f55bd8c287241b5a623c159aa134c9b3b9e9/crates/fiber/src/lib.rs#L9-L22

Is there any difference between the two?

**Comment by dhil** [comment]
The baseline implementation may work on Windows. Try to build with `cargo build --features=wasmfx_baseline`. Though, no guarantees as we currently only aim to support x64 Linux. I suppose you can build it in WSL too.

**Comment by oovm** [comment]
I am using

```toml
[dependencies.wasmtime]
version = "*"
features = ["async", "component-model", "gc", "wasmfx_baseline"]
git = "https://github.com/wasmfx/wasmfxtime"
```

and

```rust
let mut config = Config::new();
{
    // FIX: exceptions proposal not enabled
    config.wasm_exceptions(true);
    // FIX: typed continuations support is not enabled
    config.wasm_typed_continuations(true);
}
```

But always hit

https://github.com/wasmfx/wasmfxtime/blob/e21495922436f699bc45c87e10c0cfb1e18518df/crates/wasmtime/src/runtime/vm/continuation.rs#L790
